modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId="gravelmon"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="icon.png"
description='''${mod_description}'''

[[dependencies.gravelmon]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.gravelmon]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

#[[dependencies.gravelmon]]
#modId="cobblemon"
#mandatory=true
#versionRange="[1.5.0,)"
#ordering="NONE"
#side="BOTH"

[[dependencies.gravelmon]]
modId="gravels_extended_battles"
mandatory=true
versionRange="[1.5.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.gravelmon]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.gravelmon]]
modId="midnightlib"
mandatory=true
versionRange="[1.6,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "gravelmon.mixins.json"
